# Generated by Django 3.1.4 on 2020-12-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='gallerie/images/')),
                ('date', models.DateField()),
            ],
        ),
    ]
